import type { Metadata } from 'next';
import SiteFooter from '@/components/layout/SiteFooter';
import SiteHeader from '@/components/layout/SiteHeader';
import ActiveFilterChips from '@/components/catalog/ActiveFilterChips';
import MobileFilterSheet from '@/components/catalog/MobileFilterSheet';
import ProductPagination from '@/components/home/ProductPagination';
import SearchFilterPanel from '@/components/search/SearchFilterPanel';
import SearchResults from '@/components/search/SearchResults';
import SearchSortSelect from '@/components/search/SearchSortSelect';
import SearchViewToggle from '@/components/search/SearchViewToggle';
import {
  activePriceRange,
  toCategoryProducts,
  type CategoryProduct,
} from '@/lib/catalog/filter-products';
import { PRICE_BANDS, type PriceBandId } from '@/lib/catalog/price-bands';
import type { CategoryQuery } from '@/lib/catalog/query';
import { buildSearchChips, clearSearchFiltersHref } from '@/lib/search/chips';
import {
  SEARCH_PAGE_SIZE,
  hasActiveFilters,
  parseSearchQuery,
  searchHref,
  type RawSearchParams,
  type SearchQuery,
} from '@/lib/search/query';
import { SITE_NAME } from '@/lib/site';
import {
  fetchSearchProducts,
  type CategoryProductsSort,
} from '@/services/products';

/**
 * Search results, wearing the category listing's own shell.
 *
 * Deliberately not indexed. A search-results URL is generated by visitors, not
 * authored, so letting crawlers in produces unbounded near-duplicate pages
 * keyed on whatever anyone typed — the thin-content pattern
 * `sals3-geo-aeo-seo-strategy-proposal` warns about. `/c/[slug]` is the
 * indexable browse surface; this is the interactive one.
 */
export function generateMetadata(): Metadata {
  return {
    title: `Search — ${SITE_NAME}`,
    robots: { index: false, follow: true },
  };
}

const SORT_TO_API: Record<CategoryQuery['sort'], CategoryProductsSort> = {
  best: 'newest',
  'price-asc': 'price-asc',
  'price-desc': 'price-desc',
};

type SearchPageProps = {
  searchParams?: Promise<RawSearchParams>;
};

type SearchOutcome = {
  products: CategoryProduct[];
  total: number;
  totalPages: number;
  unavailable: boolean;
};

const EMPTY: SearchOutcome = {
  products: [],
  total: 0,
  totalPages: 1,
  unavailable: false,
};

async function runSearch(query: SearchQuery): Promise<SearchOutcome> {
  if (query.q === '') return EMPTY;

  const range = activePriceRange(query.band, query.priceMin, query.priceMax);

  try {
    const response = await fetchSearchProducts(query.q, {
      category: query.category,
      sort: SORT_TO_API[query.sort],
      page: query.page,
      limit: SEARCH_PAGE_SIZE,
      ...(range.minMinor > 0 ? { minPriceMinor: range.minMinor } : {}),
      ...(range.maxMinor === Infinity ? {} : { maxPriceMinor: range.maxMinor }),
    });

    return {
      products: toCategoryProducts(response.products),
      total: response.total,
      totalPages: response.totalPages,
      unavailable: false,
    };
  } catch {
    // An unreachable catalogue is not "no results" — see `SearchResults`.
    return { ...EMPTY, unavailable: true };
  }
}

/**
 * Band counts describe the keyword, not the current price filter: a count that
 * shrank to match the filter would tell a buyer that narrowing further is
 * pointless. One extra unfiltered read of the same term, and decorative enough
 * that a failure costs the counts rather than the page.
 */
async function bandCounts(
  query: SearchQuery,
): Promise<Record<PriceBandId, number>> {
  const counts = {} as Record<PriceBandId, number>;

  PRICE_BANDS.forEach((band) => {
    counts[band.id] = 0;
  });

  if (query.q === '') return counts;

  try {
    const response = await fetchSearchProducts(query.q, {
      category: query.category,
      page: 1,
      limit: SEARCH_PAGE_SIZE,
    });

    PRICE_BANDS.forEach((band) => {
      counts[band.id] = response.products.filter(
        (product) =>
          product.priceMinor >= band.minMinor &&
          product.priceMinor <= band.maxMinor,
      ).length;
    });
  } catch {
    // Decorative.
  }

  return counts;
}

function resultLine(total: number, term: string): string {
  if (total === 0) return `No results for “${term}”`;
  if (total === 1) return `1 result for “${term}”`;

  return `${total} results for “${term}”`;
}

export default async function SearchPage({ searchParams }: SearchPageProps) {
  const query = parseSearchQuery((await searchParams) ?? {});
  const [outcome, counts] = await Promise.all([
    runSearch(query),
    bandCounts(query),
  ]);

  const range = activePriceRange(query.band, query.priceMin, query.priceMax);
  const filtering = hasActiveFilters(query);
  const chips = buildSearchChips(query);
  const clearHref = clearSearchFiltersHref(query);
  const isIdle = query.q === '';
  const isEmpty = !isIdle && !outcome.unavailable && outcome.total === 0;
  const showsResults = !isIdle && !outcome.unavailable && outcome.total > 0;

  return (
    <div className="flex flex-1 flex-col bg-surface">
      <SiteHeader searchTerm={query.q} />
      <main className="mx-auto w-full max-w-6xl px-6 py-4 pb-16">
        <div className="grid grid-cols-1 items-start gap-6 lg:grid-cols-[248px_minmax(0,1fr)]">
          <aside className="hidden lg:sticky lg:top-4 lg:flex lg:flex-col">
            <SearchFilterPanel
              query={query}
              counts={counts}
              rangeIsTyped={range.typed}
              idPrefix="sidebar"
            />
          </aside>

          <div className="min-w-0">
            <h1 className="m-0 text-2xl font-bold tracking-tight text-ink">
              {isIdle ? 'Search' : `Results for “${query.q}”`}
            </h1>
            <p className="mt-1.5 mb-0 text-[13px] text-ink-muted">
              Search matches published product titles, in US dollars.
            </p>

            <div className="mt-3.5">
              <MobileFilterSheet
                activeCount={chips.length}
                applyLabel={
                  outcome.total === 1
                    ? 'Show 1 result'
                    : `Show ${outcome.total} results`
                }
                clearAllHref={clearHref}
              >
                <SearchFilterPanel
                  query={query}
                  counts={counts}
                  rangeIsTyped={range.typed}
                  idPrefix="sheet"
                />
              </MobileFilterSheet>
            </div>

            {isIdle ? null : (
              <div className="mt-3.5 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border bg-white px-3.5 py-2.5">
                <p className="m-0 text-[13px] text-ink" aria-live="polite">
                  {outcome.unavailable
                    ? 'Search unavailable'
                    : resultLine(outcome.total, query.q)}
                </p>
                <div className="flex items-center gap-3">
                  <SearchSortSelect query={query} />
                  <SearchViewToggle query={query} />
                </div>
              </div>
            )}

            {filtering ? (
              <ActiveFilterChips chips={chips} clearAllHref={clearHref} />
            ) : null}

            <SearchResults
              view={query.view}
              products={outcome.products}
              term={query.q}
              isIdle={isIdle}
              isUnavailable={outcome.unavailable}
              isEmpty={isEmpty}
              filtering={filtering}
              chips={chips}
              clearFiltersHref={clearHref}
            />

            {showsResults ? (
              <ProductPagination
                currentPage={Math.min(query.page, outcome.totalPages)}
                totalPages={outcome.totalPages}
                getPageHref={(target) => searchHref(query, { page: target })}
              />
            ) : null}
          </div>
        </div>
      </main>
      <SiteFooter />
    </div>
  );
}
